### PR TITLE
Add support for instrumenting Slime templates

### PR DESCRIPTION
**Pull request by jeffjewiss**
Hi there, I was looking to setup `elixir_plug_server_timing` in my app, however I'm using [Slime](https://github.com/slime-lang/phoenix_slime) for most of my templates. I tested this locally and was able to see timings for Slime templates in Chrome when adding this additional instrument.

I tried to follow the existing setup and style, but please let me know if you'd like to see anything changed as I'm still new to Elixir.

Cheers.

### CODE REVIEW

**Comment by cschneid** [comment]
Thank you for the contribution! We'll take a look at it soon, but it looks pretty straight forward.

**Comment by jeffjewiss** [comment]
Thanks! I just wanted to follow up on this and see if there was anything I could do to help get this accepted. Cheers!

**Comment by itsderek23** [comment]
@mitchellhenke - Mind giving this a look, and if OK, merging and doing a release? Thanks!

/cc @jeffjewiss

**Comment by mitchellhenke** [comment]
@itsderek23 yep, can do!

**Comment by mitchellhenke** [comment]
@itsderek23 Pulled down the branch and looks like everything works as expected!

image

**Comment by itsderek23** [comment]
🍾 Great!

Mind doing a new release and /cc-ing @jeffjewiss on this issue when it's cut? Thanks!

**Comment by mitchellhenke** [comment]
@jeffjewiss I've released `0.4.2` and pushed it to hex 🙂

**Comment by jeffjewiss** [comment]
Thanks for the quick turn-around on this, appreciate it!

**Pull request merged**
