### PR TITLE
Add trace Context Tracking & Reporting

### PR DESCRIPTION
**Pull request by cschneid**
To use in your application code:

ScoutApm.Context.add("email", user.email)

Keys may be Strings
Values may be Strings, Numbers, Boolean

### CODE REVIEW

**Comment by cschneid** [comment]
This will likely conflict with #5 in (relatively) minor ways. I'll wait until that lands then fixup here.

**Comment by itsderek23** [comment]
> This will likely conflict with #5 in (relatively) minor ways. I'll wait until that lands then fixup here.

Yeah - I'm OK releasing this and adjusting devtrace.

**Comment by itsderek23** [comment]
Looks good!

**Comment by itsderek23** [comment]
@cschneid - have we checked that context (user and standard) appears correctly with traces in the UI?

**Comment by itsderek23** [comment]
I verified the context is properly sent up in the payload and displayed in the ui.

**Comment by itsderek23** [comment]
This closes #13.

**Pull request merged**
